<?php

return [
    'brand' => [
        'name' => 'SENANMI',
        'tagline' => 'Tecnologia que conecta, organiza y transforma la gestion vial.',
        'logo' => 'img/lg.png',
    ],
    'meta' => [
        'title' => 'SENANMI | Gestion digital de incidentes y partes viales',
        'description' => 'SENANMI es una plataforma integral para digitalizar incidentes, accidentes, evidencias, croquis y expedientes viales desde campo hasta el CRM administrativo.',
    ],
    'media' => [
        'hero_image' => 'img/imagen_inicio.png',
        'hero_video' => '',
        'hero_poster' => '',
        'dashboard' => 'img/dashboard_crm.png',
        'app_main' => 'img/pantalla_principal.jpeg',
        'solution_image' => 'img/imagen_solucion.png',
        'demo_video' => 'https://youtu.be/qnBRu9JgZI8',
        'demo_poster' => '',
        'ecosystem' => '',
        'sketch_before' => 'img/Croquis_a_mano.png',
        'sketch_after' => 'img/croquis.jpeg',
        'sketch_video' => '',
        'pdf_preview' => 'img/reporte pdf.jpeg',
    ],
    'hero' => [
        'eyebrow' => '',
        'title' => 'Tecnologia que transforma la gestion de incidentes viales',
        'description' => 'SENANMI digitaliza el ciclo completo: reporte ciudadano, asignacion al oficial, captura en campo, evidencias, croquis, expediente PDF, CRM y estadisticas para decisiones institucionales.',
        'primary_cta' => [
            'label' => 'Solicitar demostracion',
            'href' => '#contacto',
        ],
        'secondary_cta' => [
            'label' => 'Ver video',
            'href' => '#video-demo',
        ],
    ],
    'about' => [
        'eyebrow' => 'Que es SENANMI',
        'title' => 'Un sistema para operar incidentes, accidentes y partes viales con trazabilidad',
        'description' => 'SENANMI conecta la aplicacion movil de oficiales, el CRM administrativo, la API, la base de datos centralizada y el generador de expedientes PDF para que la informacion fluya desde el lugar del accidente hasta las areas de decision.',
        'points' => [
            'Captura de informacion desde campo.',
            'Expedientes centralizados por folio.',
            'Consulta administrativa en tiempo real.',
            'Reportes PDF listos para revision, archivo o impresion.',
        ],
    ],
    'problems' => [
        ['title' => 'Procesos en papel', 'description' => 'Formatos fisicos que pueden extraviarse, deteriorarse o tardar en llegar a revision.'],
        ['title' => 'Expedientes fisicos', 'description' => 'Informacion dispersa entre carpetas, dispositivos, archivos y oficinas.'],
        ['title' => 'Mucho tiempo', 'description' => 'Captura duplicada, revision lenta y generacion manual de reportes.'],
        ['title' => 'Evidencias dispersas', 'description' => 'Fotografias y documentos guardados sin relacion clara con el folio.'],
        ['title' => 'Sin estadisticas', 'description' => 'Poca visibilidad para detectar zonas de riesgo, causas frecuentes y tiempos de atencion.'],
    ],
    'solution' => [
        'eyebrow' => 'Nuestra solucion',
        'title' => 'Del lugar del incidente al parte vial digital',
        'description' => 'SENANMI reemplaza formatos manuales, evidencias dispersas y captura duplicada por un flujo digital trazable desde campo hasta la consulta administrativa.',
        'image_caption' => 'Oficial capturando el parte vial desde el lugar del incidente',
        'steps' => [
            'Reporte del accidente',
            'Atencion del oficial',
            'Captura en SENANMI',
            'Evidencias',
            'Croquis digital',
            'Expediente PDF',
            'Consulta administrativa',
        ],
    ],
    'ecosystem' => [
        ['name' => 'CRM', 'position' => 'top'],
        ['name' => 'APP', 'position' => 'left'],
        ['name' => 'API', 'position' => 'center'],
        ['name' => 'Base de datos', 'position' => 'right'],
        ['name' => 'Reportes PDF', 'position' => 'bottom'],
    ],
    'video_demo' => [
        'eyebrow' => 'Video demostrativo',
        'title' => 'Conoce SENANMI en operacion',
        'description' => 'Mira como la plataforma acompana el flujo completo: inicio de sesion, registro del incidente, captura del parte vial, evidencias, croquis, PDF, CRM y dashboard administrativo.',
    ],
    'modules' => [
        ['title' => 'Parte Vial', 'image' => ''],
        ['title' => 'Incidentes', 'image' => ''],
        ['title' => 'Vehiculos', 'image' => ''],
        ['title' => 'Conductores', 'image' => ''],
        ['title' => 'Peatones', 'image' => ''],
        ['title' => 'Testigos', 'image' => ''],
        ['title' => 'Croquis', 'image' => ''],
        ['title' => 'Dashboard', 'image' => ''],
        ['title' => 'Usuarios', 'image' => ''],
        ['title' => 'Reportes', 'image' => ''],
    ],
    'mobile_screens' => [
        [
            'title' => 'Login',
            'description' => 'Acceso seguro para oficiales y usuarios autorizados, con una entrada clara al entorno operativo.',
            'image' => 'img/login_app.jpeg',
        ],
        [
            'title' => 'Pantalla principal',
            'description' => 'Vista inicial para consultar actividad, navegar modulos y comenzar la captura desde campo.',
            'image' => 'img/pantalla_principal.jpeg',
        ],
        [
            'title' => 'Lista de partes',
            'description' => 'Consulta de partes viales registrados, pendientes y en proceso para dar seguimiento desde la tablet.',
            'image' => 'img/listado_de_partes.jpeg',
        ],
        [
            'title' => 'Vehiculos',
            'description' => 'Registro de vehiculos involucrados con datos estructurados para evitar duplicidad y omisiones.',
            'image' => 'img/vehiculos.jpeg',
        ],
        [
            'title' => 'Conductores',
            'description' => 'Captura de informacion del conductor, licencia, estado fisico, manifestacion y datos de contacto.',
            'image' => 'img/conductores.jpeg',
        ],
        [
            'title' => 'Croquis',
            'description' => 'Representacion grafica del accidente en formato horizontal para visualizar trayectorias, puntos de impacto y elementos viales.',
            'image' => 'img/croquis.jpeg',
        ],
        [
            'title' => 'PDF',
            'description' => 'Generacion del expediente digital con informacion del parte, evidencias, croquis y datos del oficial.',
            'image' => 'img/pdf.jpeg',
        ],
    ],
    'crm_screens' => [
        [
            'title' => 'Dashboard CRM',
            'description' => 'Vista ejecutiva con indicadores, seguimiento operativo y resumen general de la informacion vial.',
            'image' => 'img/dashboard_crm.png',
        ],
        [
            'title' => 'Listado de partes viales',
            'description' => 'Consulta centralizada de folios, estatus, fechas y registros generados desde campo.',
            'image' => 'img/listado_partesviales.png',
        ],
        [
            'title' => 'Detalle del expediente',
            'description' => 'Revision completa del parte vial con datos relacionados, evidencias y trazabilidad administrativa.',
            'image' => 'img/detalle.png',
        ],
        [
            'title' => 'Usuarios y permisos',
            'description' => 'Administracion de accesos, roles y personal autorizado para operar la plataforma.',
            'image' => 'img/usuarios.png',
        ],
        [
            'title' => 'Catalogos administrativos',
            'description' => 'Configuracion de datos base para adaptar SENANMI a los procesos de cada institucion.',
            'image' => 'img/catalogos.png',
        ],
    ],
    'sketch' => [
        'eyebrow' => 'Croquis inteligente',
        'title' => 'Del croquis manual a una representacion digital clara y trazable',
        'description' => 'Con SENANMI, el oficial puede elaborar el croquis directamente en la tablet usando plantillas, elementos viales, vehiculos, trayectorias, senalamientos y puntos de impacto. El resultado queda asociado al folio y forma parte del expediente digital.',
        'benefits' => [
            'Estandariza la representacion del accidente.',
            'Evita croquis ilegibles o incompletos.',
            'Relaciona el dibujo con evidencias, personas y vehiculos.',
            'Permite integrarlo al expediente PDF.',
        ],
    ],
    'benefits' => [
        'Reduce tiempos de captura y revision',
        'Digitaliza procesos operativos',
        'Centraliza informacion por folio',
        'Permite consulta inmediata',
        'Da mayor control administrativo',
        'Genera mejores estadisticas',
        'Reduce el uso de papel',
        'Fortalece la transparencia',
    ],
    'technologies' => [
        'PHP',
        'MySQL',
        'React Native',
        'REST API',
        'JWT',
        'Google Maps',
        'Leaflet',
        'Fabric.js',
        'Bootstrap',
        'AdminLTE',
    ],
    'gallery' => [
        ['title' => 'CRM', 'image' => ''],
        ['title' => 'App', 'image' => ''],
        ['title' => 'Croquis', 'image' => ''],
        ['title' => 'PDF', 'image' => ''],
        ['title' => 'Dashboard', 'image' => ''],
        ['title' => 'Incidentes', 'image' => ''],
        ['title' => 'Mapa', 'image' => ''],
        ['title' => 'Reportes', 'image' => ''],
    ],
    'operational_flow' => [
        'Ciudadano',
        'C4',
        'Oficial',
        'Aplicacion',
        'Servidor',
        'CRM',
        'PDF',
        'Consulta',
    ],
    'stats' => [
        ['value' => '+20', 'label' => 'Modulos operativos'],
        ['value' => '100%', 'label' => 'Proceso digital'],
        ['value' => '24/7', 'label' => 'Disponibilidad operativa'],
        ['value' => 'Tiempo real', 'label' => 'Consulta y seguimiento'],
        ['value' => 'Miles', 'label' => 'Registros centralizados'],
        ['value' => 'PDF', 'label' => 'Reportes automaticos'],
    ],
    'faqs' => [
        [
            'question' => 'Funciona sin internet?',
            'answer' => 'La aplicacion puede prepararse para capturar informacion en campo y sincronizarla cuando exista conexion, segun el alcance tecnico definido para la institucion.',
        ],
        [
            'question' => 'Como se generan los PDFs?',
            'answer' => 'SENANMI toma la informacion registrada en el parte vial, evidencias y croquis para construir un expediente digital listo para consulta, descarga o impresion.',
        ],
        [
            'question' => 'Como se integra con otros sistemas?',
            'answer' => 'SENANMI puede coordinarse con otras dependencias cuando el municipio lo requiera, como C4, C5, policia, proteccion civil o Cruz Roja para atender casos extremos con mayor rapidez y control.',
        ],
        [
            'question' => 'Se puede personalizar?',
            'answer' => 'Si. Los catalogos, roles, permisos, flujos y formatos pueden adaptarse a los procesos de cada municipio o dependencia.',
        ],
    ],
    'contact' => [
        'title' => 'Solicita una demostracion de SENANMI',
        'description' => 'Escribenos por correo o WhatsApp para agendar una demostracion y revisar como SENANMI puede adaptarse a la operacion de tu institucion.',
        'email' => 'fgarcia@workflex.mx',
        'phone' => '+52 81 3980 8035',
        'whatsapp' => '528139808035',
        'address' => 'Humberto Junco Voigt 2307, Valle Oriente, 66266 San Pedro Garza Garcia, N.L.',
    ],
];
